services:
  frontend:
    build:
      context: ./receipt-project
    image: frontend-receipts-scanner-web
    ports:
      - "3000:3000"
    volumes:
      - ./receipt-project:/app
      - ./receipt-project/.env.local:/app/.env.local
